Override icon with an image URL
kalkih/mini-media-player pull request #639
Opened 2022-04-05 08:12 UTC by jampez77

added image attribute to override icon with a URL.

2022-04-05 08:35 UTC, jampez77 commented
Not sure why this is failing, any help would be appreciated.

2022-04-11 20:27 UTC, kalkih commented
Sorry the build pipeline was broken on the `dev` branch, it's now fixed, please do a `commit --amend` and then a `push --force`, or rebase the dev branch and push.

2022-04-12 14:54 UTC, kalkih requested changes

2022-04-12 22:14 UTC, kalkih approved these changes

2022-04-12 22:15 UTC, merged